### ISSUE TITLE
Not able to pass token into API after refactoring

### ISSUE THREAD

**Issue by scshull119** [scshull119/group_project_3#11]
After refactoring to eliminate multiple layout.html.erb files, I am no longer to get JSON data to reliably load into my Backbone views and map.  Using byebug and the Ruby console, I have determined that this is due to aborted Ajax requests because a user token can't be found.  Before the refactor, all of our .js files were linked through manifests in the header, but some are now referenced directly in the views and these are the ones that are causing problems.  

Message from Ruby console is as follows:
"Started GET "/api/ratings/map_ratings" for ::1 at 2015-09-15 16:26:40 -0400
Processing by Api::RatingsController#map_ratings as JSON
Filter chain halted as :current_api_user! rendered or redirected
Completed 200 OK in 1ms (Views: 0.1ms | ActiveRecord: 0.0ms)"

**Comment by rapala61** [comment]
in person
