### ISSUE TITLE
Need some advice on submitting input from a form to our API

### ISSUE THREAD

**Issue by scshull119** [scshull119/group_project_3#15]
I have a few options:

1) My AJAX post request through Backbone is working great, however I also want a page redirect to happen when the user clicks submit, and the AJAX request doesn't provide that.

2) I could alternatively input using a regular HTML form making a post request and redirect in my Rails controller.  I am having trouble getting that to work with token authentication on the API (getting 200/401 not authorized errors).

3)  I have looked into using window.replace('url') in my form.on('submit') function to simulate a page redirect.  Thoughts?  Any potential drawbacks to using this method?  It seems like a bit of a messy workaround to me.

**Comment by emilylordahl** [comment]
Just spoke with Sam about this. @rapala61 or @amadden80 do you have thoughts on what might be a better practice on this?

**Comment by amadden80** [comment]
I'd argue for not using AJAX if you want to change the page you're on.  You may need to include a 
`<%= token_tag %>` to make sure your form has the authenticity token.
