### ISSUE TITLE
How do I pull the updated version of the files?

### ISSUE THREAD

**Issue by eerlikh** [scshull119/group_project_3#2]
I do a git pull origin master and it says I'm up to date. 

I do a git pull upstream master and it says :

group_project_3 FutureChild$ git pull upstream master
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

So it seems I still don't have rights or access to the repo for some reason.

**Comment by emilylordahl** [comment]
Were you all able to get this resolved?
