### ISSUE TITLE
Still could use some help with authenticity token

### ISSUE THREAD

**Issue by scshull119** [scshull119/group_project_3#22]
Following up on my issue from yesterday.  I am still having a bit of trouble refactoring my form to use <%= authenticity_token %>.  I would like to perform a POST request from a standard vanilla HTML form to my rails API without having to rely on Ajax or Backbone.

**Comment by scshull119** [comment]
Current behavior:  
I've inserted <%= hidden_field_tag :authenticity_token, form_authenticity_token %> into a form in my new_rating.html.erb.  Upon submitting the form, I get a response of:

{
200: 401
}

Is there anything else I need to do to make this work?  I am honestly very shaky on my understanding of this type of form validation, and thus far I've failed to find any documentation that really clarifies it.

Thanks!

**Comment by amadden80** [comment]
I believe it is `<%= token_tag %>` ?

In application controller... if you remove the protection line... does it work?

**Comment by emilylordahl** [comment]
How's it going on this?

**Comment by scshull119** [comment]
I solved it.  Thanks Emily!

- Sam

**Comment by emilylordahl** [comment]
Hooray! No problem!
