### ISSUE TITLE
redirect not working when no user is logged in

### ISSUE THREAD

**Issue by scshull119** [scshull119/group_project_3#8]
We are trying to test our redirect code to make sure users cannot access our data without being logged in.  

We are getting an Abstract Contoller::DoubleRenderError message because it seems that the server is trying to render and redirect at the same time rather than choosing one or the other based on the user's logged-in status.

**Comment by amadden80** [comment]
```ruby
def authenticate!
  if current_user
    return true
  else
    redirect_to root_path
    return false
  end
end
```

```ruby
def profile
   return nil if !authenticate!
   render layout: 'my-fancy-layout'
end
```
